"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    question: "What types of datasets can Artha AI generate?",
    answer:
      "Currently we generate text datasets with sentiment, topic classification and named entity recognition labels in Hindi, Gujarati, Marathi, Tamil and English. For custom vision, audio or document datasets use our Custom Dataset service.",
  },
  {
    question: "How accurate are the labels?",
    answer:
      "Our average confidence score is 98.8%. Every label is generated by Groq AI and only rows scoring above 80% confidence are included in your final dataset. You can see the full quality report before downloading.",
  },
  {
    question: "Where does the data come from?",
    answer:
      "We collect real data from Google Play Store reviews, YouTube comments and Indian news websites. We never use synthetic or fake data.",
  },
  {
    question: "How long does generation take?",
    answer:
      "Most datasets complete in 10-20 minutes depending on language and quantity. Gujarati and Tamil may take slightly longer due to fewer available online sources.",
  },
  {
    question: "Can I request a custom dataset?",
    answer:
      "Yes. Use our Custom Dataset page to describe exactly what you need — any domain, language, format or label type. We will get back within 24 hours. Email: arthaai.dev@gmail.com",
  },
  {
    question: "What formats can I download?",
    answer:
      "CSV, JSON, Excel (.xlsx), Parquet and HuggingFace Dataset format. All formats include a metadata.json with full quality report.",
  },
  {
    question: "What if my dataset has quality issues?",
    answer:
      'Use the "Report a data quality issue" button on your download page. We review every report within 24 hours and will regenerate if needed.',
  },
  {
    question: "Is there a free trial?",
    answer:
      "Yes. During beta you can generate datasets up to 300 rows per language completely free.",
  },
];

export default function FaqAccordion() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="space-y-3">
      {faqs.map((faq, index) => {
        const isOpen = openIndex === index;
        return (
          <div key={faq.question} className="rounded-2xl border border-gray-700 bg-[#1E293B]">
            <button
              type="button"
              onClick={() => setOpenIndex(isOpen ? null : index)}
              className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"
            >
              <span className="text-sm font-semibold text-white sm:text-base">{faq.question}</span>
              <ChevronDown className={`h-5 w-5 shrink-0 text-gray-300 transition-transform ${isOpen ? "rotate-180" : "rotate-0"}`} />
            </button>
            {isOpen && (
              <div className="border-t border-gray-700 px-5 pb-5 text-sm leading-6 text-gray-300">
                {faq.answer}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
